### ISSUE TITLE
Won't compile for new firmwares

### ISSUE THREAD

**Issue by asin9749** [Xorboo/root-of-life#2]
applications_user/roots_of_life_game/roots_of_life_game.c: In function 'roots_draw_callback': applications_user/roots_of_life_game/roots_of_life_game.c:568:24: error: implicit declaration of function 'acquire_mutex' [-Werror=implicit-function-declaration] 568 | GameState* state = acquire_mutex((ValueMutex*)ctx, 25); | ^~~~~~~~~~~~~ applications_user/roots_of_life_game/roots_of_life_game.c:568:39: error: 'ValueMutex' undeclared (first use in this function) 568 | GameState* state = acquire_mutex((ValueMutex*)ctx, 25); | ^~~~~~~~~~ applications_user/roots_of_life_game/roots_of_life_game.c:568:39: note: each undeclared identifier is reported only once for each function it appears in applications_user/roots_of_life_game/roots_of_life_game.c:568:50: error: expected expression before ')' token 568 | GameState* state = acquire_mutex((ValueMutex*)ctx, 25); | ^ applications_user/roots_of_life_game/roots_of_life_game.c:603:5: error: implicit declaration of function 'release_mutex' [-Werror=implicit-function-declaration] 603 | release_mutex((ValueMutex*)ctx, state); | ^~~~~~~~~~~~~ applications_user/roots_of_life_game/roots_of_life_game.c:603:31: error: expected expression before ')' token 603 | release_mutex((ValueMutex*)ctx, state); | ^ applications_user/roots_of_life_game/roots_of_life_game.c:567:61: error: unused parameter 'ctx' [-Werror=unused-parameter] 567 | static void roots_draw_callback(Canvas* const canvas, void* ctx) { | ~~~~~~^~~ applications_user/roots_of_life_game/roots_of_life_game.c: In function 'roots_of_life_game_app': applications_user/roots_of_life_game/roots_of_life_game.c:681:5: error: unknown type name 'ValueMutex' 681 | ValueMutex state_mutex; | ^~~~~~~~~~ applications_user/roots_of_life_game/roots_of_life_game.c:682:9: error: implicit declaration of function 'init_mutex' [-Werror=implicit-function-declaration] 682 | if(!init_mutex(&state_mutex, state, sizeof(GameState))) { | ^~~~~~~~~~ applications_user/roots_of_life_game/roots_of_life_game.c:705:40: error: implicit declaration of function 'acquire_mutex_block' [-Werror=implicit-function-declaration] 705 | GameState* state = (GameState*)acquire_mutex_block(&state_mutex); | ^~~~~~~~~~~~~~~~~~~ applications_user/roots_of_life_game/roots_of_life_game.c:745:5: error: implicit declaration of function 'delete_mutex' [-Werror=implicit-function-declaration] 745 | delete_mutex(&state_mutex); | ^~~~~~~~~~~~ cc1: all warnings being treated as errors scons: *** [build/f7-firmware-C/.extapps/roots_of_life_game/roots_of_life_game.o] Error 1

**Comment by Xorboo** [comment]
Thanks for noticing, fixed in [latest commit](https://github.com/Xorboo/root-of-life/commit/f46ebd5984401c50ce809b58375d81f093453e08)
